### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by gsotnikov** [bryandlee/FreezeG#1]
The results look very ambitious! When do you plan to publish a paper or open share code, presenting them?
Thanks!

**Comment by bryandlee** [comment]
Hi, thanks for the interest! 
I'm just playing around with the generative models and testing out some random ideas. I'm doing it for fun, so not really planning to publish or present anything unless there is a significant technical contribution that I want to share. This is a simple method, and probably not what you thought it was, but I added some details in the README so you can check out.

**Comment by afiaka87** [comment]
Since you seem somewhat underwhelmed by your own results, can you provide any other repositories which explore these same ideas?

If not, then I'd say what you have here is absolutely a significant technical contribution! Looks great, good job. 

Edit: Apologies, I just now saw the linked research papers. Those are a goldmine! 

Anyone looking for a similar approach with released code and training data can check out this repository: 

https://github.com/sagiebenaim/OneShotTranslation

**Comment by bryandlee** [comment]
You can also checkout these repos:

TUNIT
https://github.com/clovaai/tunit

StarGAN2
https://github.com/clovaai/stargan-v2

FUNIT
https://github.com/NVlabs/FUNIT

These do not share the same idea, but it would be interesting to apply the freezing technique to these methods.

**Comment by gsotnikov** [comment]
Thank you for response, but it is still not clear for me. As far as I understood, you have done the following: took the pretrainied StyleGAN2 on FFHQ (in case of img2portrait) and fixed the few early blocks (e.g. until resolution 32). Then you have trained only later blocks on a new task - generating MetFaces. As this models shares a few blocks of weights the generated samples share semantics (given the same latent code) and it is called "pseudo" translation as you do not implicitly encode a new image but can "translate" it via forward pass with a fine-tuned model, am I right?

**Comment by bryandlee** [comment]
Yes, precisely.
