### ISSUE TITLE
Regarding the datasets

### ISSUE THREAD

**Issue by utkarshojha** [bryandlee/FreezeG#2]
Thanks for the nice experiments. I was wondering if you plan to release the dataset for cropped simpsons/malnyun faces. And how many images did you use for the simpsons experiment?

**Comment by bryandlee** [comment]
At the moment, I don't think I can share Malnyun dataset because of copyright issues. 

The Simpsons dataset can be found on Kaggle:
https://www.kaggle.com/kostastokis/simpsons-faces

For the experiment, I manually selected 1k images from the original set and resized it to 256. You can download it from the link:
https://drive.google.com/file/d/1cHGfb66d3EqIZkcImc_i2mV4tkL6Al3H/view

**Comment by utkarshojha** [comment]
oh awesome, thank you so much!
